### ISSUE TITLE
Cannot read property 'nwDispatcher' of undefined

### ISSUE THREAD

**Issue by sunojvijayan** [cgrossde/nw-notify#18] opened 2016-01-14 08:22 UTC
Getting this issue

**Comment by cgrossde** [comment] 2016-01-14 10:35
A little bit more details please: code that leads to the error and a stack trace would be helpful.

**Comment by cgrossde** [comment] 2016-01-31 19:07
Will close this due to missing information on how to reproduce the problem

**Closed by cgrossde** 2016-01-31 19:07 UTC
